name: Deploy Project
on:
  # Run this workflow every time something is pushed to the main branch
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
     # 1. Checkout the project code from the main branch
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          ref: main

        # Ensure Git is set up correctly in the container
      - name: Mark repository as safe
        run: git config --global --add safe.directory /__w/Campus-Navigation-App/Campus-Navigation-App

        #ensure git is configured
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci
        #istall dependencies
      - name: Install EAS CLI
        run: npm install -g eas-cli

      #aunthenticate with expo
      - name: Authenticate with Expo
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        run: eas whoami

      - name: Deploy to Expo Hosting
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        run: eas update --branch production --message "Deployed from GitHub Actions"